### ISSUE TITLE
What is destination?

### ISSUE THREAD

**Issue by rmpt** [dma-ais/AisLib#100]
From the examples, to send a message we need to do something like this:

```
var aisReader = AisReaders.createReader(host, port);
aisReader.start();

// Make AIS message 12
AisMessage12 msg12 = new AisMessage12();
msg12.setDestination(destination);
msg12.setMessage("Hello");
```

But what is `destination` and how to use it?

**Comment by dimitrispallas** [comment]
@rmpt 
the destination variable is the MMSI number of the station which is the destination of the message. I hope this answers your question.
