### ISSUE TITLE
AisLib packet.getTimestamp is null when used in spark environment

### ISSUE THREAD

**Issue by manasdebashiskar** [dma-ais/AisLib#12]
Hi, 
 I am using AisLib to parse Ais Messages in a apache spark environment backed by HDFS.
 I am using few simple steps like 
1) parse the message.
2) map only the timestamp and UserId of each message.
3) Save it to HDFS.
Result: I see that my timestamp(Date field) is null all along. 
PS: When I pretty print only few of my messages of the RDD the result looks just fine.

**Comment by kaspernielsen** [comment]
Can I close this issue?
