### ISSUE TITLE
Push AisLib to version eye

### ISSUE THREAD

**Issue by mablae** [dma-ais/AisLib#14]
It would be great if VersionEye could be updated regularly.

As of today VersionEye lists v0.5.2 :
https://www.versioneye.com/java/aislib:aislib/0.5.2

VersionEye has support for Github

**Comment by kaspernielsen** [comment]
I think it is a different library http://software.ais.pl/aislib/

**Comment by mablae** [comment]
Ohje, even worse ;-)

**Comment by reiz** [comment]
@mablae @kaspernielsen We track everything on search.maven.org, jCenter and a handful other MVN Repositories. Why not deploy this package to search.maven.org? That way it would be easy accessible for everybody and it wold appear automatically at VersionEye. What do you think?

**Comment by kaspernielsen** [comment]
Will be fixed via https://github.com/dma-ais/AisLib/issues/15
