### ISSUE TITLE
Maven dependency for AisLib does not work

### ISSUE THREAD

**Issue by manasdebashiskar** [dma-ais/AisLib#19]
I don't know if it is me or something wrong with the artifacts are published but I get the following error when I try to include ais-lib to my sbt build.
[warn] io problem while parsing ivy file: http://repository-dma.forge.cloudbees.com/snapshot/dk/dma/ais/lib/ais-parent/2.2/ais-parent-2.2.pom: Impossible to load parent for file:/home/USERME/.ivy2/cache/dk.dma.ais.lib/ais-parent/ivy-2.2.xml.original. Parent=dk.dma#dma-root-pom;21

..Manas

**Comment by manasdebashiskar** [comment]
It seems that the release repo works where as the snapshot repo is where the problem is.

**Comment by kaspernielsen** [comment]
Dont know much about Ivy. But dma-root-pom is not located on the central repository
Try adding something like this to your setup

	<repository>
			<id>dma-releases</id>
			<name>Dma Release Repository</name>
			<url>http://repository-dma.forge.cloudbees.com/release/</url>
		</repository>
        <repository>
            <id>dma-snapshots</id>
            <name>Dma Release Repository</name>
            <url>http://repository-dma.forge.cloudbees.com/snapshot/</url>
        </repository>

**Comment by borchsenius** [comment]
dma-root-pom v. 25 is in the central repository now. 
[https://search.maven.org/artifact/dk.dma/dma-root-pom/25/pom](https://search.maven.org/artifact/dk.dma/dma-root-pom/25/pom)

Ivy.
`<dependency org="dk.dma" name="dma-root-pom" rev="25" />`
