### ISSUE TITLE
AisLib 2.3 release?

### ISSUE THREAD

**Issue by MikaelUlvesjo** [dma-ais/AisLib#24]
Hi

It is 10 months since  2.2 release, my question is when 2.3 is due to be released.
I know that there are not any big changes but I need the two I have sent pull requests on ( #18  and #23 ).

**Comment by tbsalling** [comment]
6 years later ... 2.4 was released on Oct 24, 2019 - https://mvnrepository.com/artifact/dk.dma.ais.lib/ais-lib-messages

To the best of my knowledge there's no current funding or maintenance of this project.
