### ISSUE TITLE
fasterxml/jackson dependency update?

### ISSUE THREAD

**Issue by ejokeeffe** [dma-ais/AisLib#34]
I've been trying to pipe AIS messages into AWS kinesis using the AisLib library (which is fantastic by the way - thank you!) and the AWS sdk (aws-java-sdk-bom, version 1.11.220). Consuming the messages using AisLib works great but the code fails on the aws sdk code calls. It seems the aws sdk probably uses a more updated version of fasterxml:

`Exception in thread "main" java.lang.NoSuchMethodError: com.fasterxml.jackson.annotation.JsonProperty.access()Lcom/fasterxml/jackson/annotation/JsonProperty$Access;`

When I build the project, the version of fasterxml installed is 2.4

`  <classpathentry kind="var" path="M2_REPO/com/fasterxml/jackson/core/jackson-annotations/2.4.0/jackson-annotations-2.4.0.jar"/>`

It looks like 2.9.2 is the most up to date version, although I don't know which version the aws sdk is using. Are there plans to update the version of fasterxml/jackson that is being used? Or can you suggest a workaround that I could use?

**Comment by tbsalling** [comment]
Thank you for using and complementing AisLib!

There are no current plans to fix this issue with AWS - but it would be much appreciated if you could supply us with a pull request which brings AisLib to use a newer version of Jackson/fasterXML (which incidentally would also make your AWS solution happy :-)). If you do so, I'll review it and incorporate it into the master branch.

**Comment by ejokeeffe** [comment]
Hi @tbsalling  - I'm afraid that's where I'm a bit stuck. I can't see where Jackson/fasterXML is identified as a dependency. It's not within the poms in AisLib (that i could see) so I'm assuming it's in dma-root-pom or dk-dma-commons?

**Comment by tbsalling** [comment]
Hmm... ok, I'll take a look when I get time. But unfortunately I can't promise any specific deadline at the moment.

**Comment by ejokeeffe** [comment]
@tbsalling  - thanks for looking into it. No panic!

I can do a workaround for now.

**Comment by CallSign-Filter** [comment]
Suggest this issue be closed, the dependency was here: https://github.com/dma-ais/AisLib/blob/master/ais-lib-json/pom.xml and was updated

**Comment by ejokeeffe** [comment]
@CallSign-Filter Happy to close.Thanks.
