### ISSUE TITLE
AisMessage27 does not encode gnssPosStatus

### ISSUE THREAD

**Issue by Zoybean** [dma-ais/AisLib#39]
`AisMessage27::getEncoded` returns a `SixbitEncoder` with 95 bits, missing the 1 bit `gnssPosStatus` field. Given `AisMessage27::parse` expects a `BinArray` with 96 bits, and reads `gnssPosStatus`, it seems this was an accidental omission, and it likely missed discovery due to #38.

**Comment by tbsalling** [comment]
Hi @Zoybean - thanks; your contribution is welcomed. 

Would it be possible for you to supply me at pull request adding the missing functionality? Preferably including unit test.

Thanks,
/Thomas.
