### ISSUE TITLE
Serial Connection?

### ISSUE THREAD

**Issue by tobermory** [dma-ais/AisLib#40]
The README Introduction suggests AisLib can handle AIS data arriving on a serial connection.  Yet I don't see any classes anywhere that do indeed handle serial.  Am I missing something here?  I know Java's serial reading support is not perfect, and myself have used rxtx in the past, so expected to see use of that lib or similar in the AisLib dependency tree.

**Comment by tbsalling** [comment]
You are right, that the README mentions serial connections as an example source of AIS messages. 

However, there are no classes in AisLib to handle serial communications. The communications layer is purposely intended to be kept outside of AisLib - so perhaps we should adjust the wording a bit.
