### ISSUE TITLE
Multiple Line Messages

### ISSUE THREAD

**Issue by usmcphysicist** [dma-ais/AisLib#43]
Does this API support messages that are more than one line long? It looks like it should in the `SentenceLine.java` class but I cannot figure out how to send the encoded data into it to make it work. Perhaps documentation or code comments to suppliment?

**Comment by tbsalling** [comment]
Yes, it does.  Paired sentences like this can be parsed:

```
!AIVDM,2,1,4,B,55MwW7P00001L@?;GS0<51B08Thj0TdpE800000P0hD556IE07RlSm6P0000,0*0B
!AIVDM,2,2,4,B,00000000000,2*23
```

**Comment by usmcphysicist** [comment]
Perhaps I was unclear, but I was looking for help as how to do this. I figured it out but it was not very intuitive so I will leave this here so others may see. 
`
Vdm vdm1 = new Vdm();
vdm1.parse("!AIVDM,2,1,4,B,55MwW7P00001L@?;GS0<51B08Thj0TdpE800000P0hD556IE07RlSm6P0000,0*0B");
vdm1.parse("!AIVDM,2,2,4,B,00000000000,2*23");

AisMessage aisMessage = AisMessage.getInstance(vdm1);
assert aisMessage instanceof AisMessage5;
`
I would suggest putting something to this effect in the README

**Comment by mikeshedrack** [comment]
How can i create a two fragments sentences like that one above

**Comment by mikeshedrack** [comment]
> Yes, it does. Paired sentences like this can be parsed:
> 
> ```
> !AIVDM,2,1,4,B,55MwW7P00001L@?;GS0<51B08Thj0TdpE800000P0hD556IE07RlSm6P0000,0*0B
> !AIVDM,2,2,4,B,00000000000,2*23
> ```

How can i encode paired sentences
