### ISSUE TITLE
Message24 modern format

### ISSUE THREAD

**Issue by bushaev** [dma-ais/AisLib#44]
With new [ITU spec (version 5)](https://www.itu.int/rec/R-REC-M.1371-5-201402-I/en) which came out in 2014, Message24 part B has been changed, compared to previous version. Specifically last 6 bits of part B message had been spare bits, but with version 5 first 4 bits are now indicating `epfd` filled. Should AisLib be updated for these changes ? I'd be happy to do a pull-request.

**Comment by tbsalling** [comment]
Hi @bushaev - your contribution would be very much welcomed. If possible, please include a unit test in the pull request; then I'll review and merge it to master.
