### ISSUE TITLE
Message 24, Mothership MMSI

### ISSUE THREAD

**Issue by mvlcek** [dma-ais/AisLib#5]
According to http://gpsd.berlios.de/AIVDM.html for auxiliary crafts, the mothership MMSI is transferred instead of the dimensions. Any support planned?

In order to read data in an extended Message class the message parsing should be done in parse(binArray), not parse() and BinArray should include methods reset() and skip(bits). Currently it is not practical to do the change in an extended class.

**Comment by panoet** [comment]
According to this page, [type 24](https://gpsd.gitlab.io/gpsd/AIVDM.html#_type_24_static_data_report) actually need more works.
