### ISSUE TITLE
Another error : AisLib building 

### ISSUE THREAD

**Issue by emailnyaoki** [dma-ais/AisLib#51]
I tried your solution on a closed issue "AisLib is not building". The different error came up.

[INFO] Scanning for projects...
Downloading from dma-releases: http://repository-dma.forge.cloudbees.com/release/dk/dma/dma-root-pom/24/dma-root-pom-24.pom
Downloading from central: https://repo.maven.apache.org/maven2/dk/dma/dma-root-pom/24/dma-root-pom-24.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for dk.dma.ais.lib:ais-parent:2.4-SNAPSHOT: Could not transfer artifact dk.dma:dma-root-pom:pom:24 from/to dma-releases (http://repository-dma.forge.cloudbees.com/release/): repository-dma.forge.cloudbees.com and 'parent.relativePath' points at wrong local POM @ line 5, column 10
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project dk.dma.ais.lib:ais-parent:2.4-SNAPSHOT (C:\Users\Kafilah\AisLib\pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for dk.dma.ais.lib:ais-parent:2.4-SNAPSHOT: Could not transfer artifact dk.dma:dma-root-pom:pom:24 from/to dma-releases (http://repository-dma.forge.cloudbees.com/release/): repository-dma.forge.cloudbees.com and 'parent.relativePath' points at wrong local POM @ line 5, column 10: Unknown host repository-dma.forge.cloudbees.com -> [Help 2]
[ERROR]

Thanks

Regards,
Oki

**Comment by borchsenius** [comment]
version 25 of the root pom is available in the central repository now [https://search.maven.org/artifact/dk.dma/dma-root-pom/25/pom](https://search.maven.org/artifact/dk.dma/dma-root-pom/25/pom)
