### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by bmottin** [dma-ais/AisLib#54]
![image](https://user-images.githubusercontent.com/56408148/66599696-d93d0f00-eb71-11e9-99f3-be42934aadd8.png)

Today I downloaded and attempted to compile and got the error you see in the screenshot I took. Following the advice of the admin here:

https://github.com/dma-ais/AisLib/issues/48

I am able to compile without issue using the following commands...

git clone https://github.com/dma-dk/dma-developers.git
cd dma-developers/rootpom/
mvn clean install -DskipTests
cd ../..
git clone https://github.com/dma-enav/e-Navigation.git
cd e-Navigation/
mvn clean install -DskipTests
cd ..
git clone https://github.com/dma-dk/dma-commons.git
cd dma-commons/
mvn clean install -DskipTests
cd ..
git clone https://github.com/kaspernielsen/codegen.git
cd codegen
mvn clean install -DskipTests
cd ..
git clone https://github.com/MaritimeConnectivityPlatform/MaritimeCloud.git
cd MaritimeCloud
sed -i 's/0.1/0.8-SNAPSHOT/' mc-msdl/mc-msdl-javagenerator/pom.xml
mvn clean install -DskipTests
cd ..
git clone https://github.com/dma-ais/AisLib.git
cd AisLib/
mvn clean install -DskipTests

Is there still an issue with the artifacts for this project? I'm on Centos 7.6 and I'm running maven  v3.6.2.

**Comment by borchsenius** [comment]
The dependencies needed for building AisLib have been added to maven central.
Everybody should be able to build AisLib with $ mvn clean install now
@bmottin try pulling the latest changes and rebuild. Please share your results

**Comment by bmottin** [comment]
I believe the issue still remains. I did a fresh git clone from the repo and it built fine. Then I deleted the .m2 repo dir in my home directory and tried to rebuild with a clean system. The same issue persists.

![image](https://user-images.githubusercontent.com/56408148/67569275-72386200-f6fc-11e9-8ada-f866851ec1da.png)

**Comment by borchsenius** [comment]
According to this public build [https://travis-ci.org/dma-ais/AisLib](https://travis-ci.org/dma-ais/AisLib) it should be possible to do a clean build.
[![Build Status](https://travis-ci.org/dma-ais/AisLib.svg?branch=master)](https://travis-ci.org/dma-ais/AisLib)
Can you provide the complete build log? (more than the screenshot)

**Comment by bmottin** [comment]
Absolutely!

[AisLib_build.log](https://github.com/dma-ais/AisLib/files/3772132/AisLib_build.log)

**Comment by borchsenius** [comment]
Thank you! 
I have just [committed](https://github.com/dma-ais/AisLib/commit/715c1f0f39845725f23cf978a7f476b910710dae) a change that allows snapshots version from the oss.sonatype.org's staging repository.
Try pulling the latest version and do a clean build again

**Comment by bmottin** [comment]
Build succeeded! Thank you!

**Comment by borchsenius** [comment]
great 👍
