### ISSUE TITLE
VDM parser and decimal places

### ISSUE THREAD

**Issue by Fabiest** [dma-ais/AisLib#58]
Hello,

I've been looking at AisLib, specially the vdm parser and have some questions regarding decimal values.
When parsing latitude/longitude i get int/long but there is a field resolution which i believe can be used to obtain the proper value of lat/lon. For other cases i don't see the same, things like rog, sog, heading, etc. How can i know the decimal parts? Is it like a convention that, example, the first 2 digits are the integer part and the others the decimal?
If you could point me to some documentation, that would help.

**Comment by mith-emsa** [comment]
This was an old question and is not really an issue of the library
