### ISSUE TITLE
AisLib v2.4 published with invalid dependencies to maven central repo

### ISSUE THREAD

**Issue by sta4152** [dma-ais/AisLib#69]
In the ais-parent-2.4 POM as being release and published to central maven repos, the dependency towards
 - dk.dma.enav:enav-util is defined with property dependencies.enav.version=0.6-SNAPSHOT and 
 - dk.dma.commons:dma-commons-util is defined with property dependencies.dma.commons.version=0.5-SNAPSHOT

Please note the "-SNAPSHOT" suffixes, those are wrong. No such versions were published to maven central repos obviously, but the final ones, 0.6 (enav-util) and 0.5 (dma-commons-util).

This makes projects depending on AisLib 2.4 to fail on maven build.

This was fixed meanwhile with commit "Update dependencies" (8190d2cf3c2573e85c6e398d21218be74c408e3f). But one is unable to pull the dependencies from the public maven repos as defined for the released version 2.4.

Please create and publish a new release having this fixed.

**Comment by elopezp** [comment]
Same issue with ais-lib-communication in Maven. My dependency is next: 
```
		<dependency>
			<groupId>dk.dma.ais.lib</groupId>
			<artifactId>ais-lib-communication</artifactId>
			<version>2.4</version>
		</dependency>
```
 I tried to compile maven pom.xml and I get the following:

`The following artifacts could not be resolved: dk.dma.enav:enav-model:jar:0.6-SNAPSHOT, dk.dma.commons:dma-commons-util:jar:0.5-SNAPSHOT, dk.dma.enav:enav-util:jar:0.6-SNAPSHOT: Could not find artifact dk.dma.enav:enav-model:jar:0.6-SNAPSHOT[m`

Any update about this issue?

**Comment by tbsalling** [comment]
To the best of my knowledge this project is no longer funded or actively maintained (anyone - correct me if wrong). 

A hint to solve the problem above is to clone and compile this project locally: https://github.com/dma-enav/e-Navigation.

**Comment by dcaillia** [comment]
You can patch it by having this in your pom.xml

	<dependencyManagement>
		
		<dependencies>
			<dependency>
				<groupId>dk.dma.enav</groupId>
				<artifactId>enav-model</artifactId>
				<version>0.6</version>
			</dependency>
			<dependency>
				<groupId>dk.dma.enav</groupId>
				<artifactId>enav-util</artifactId>
				<version>0.6</version>
			</dependency>
			<dependency>
				<groupId>dk.dma.commons</groupId>
				<artifactId>dma-commons-util</artifactId>
				<version>0.5</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
